# Workflow for closing the loop.
# Its only job is to run the full training pipeline from end-to-end.
# It is triggered ONLY by an API call from our main validation workflow when it detects significant data drift.

name: Automated Retraining Pipeline

on:
  # This workflow can only be started via an API call (or manually from the Actions tab).
  # It will NOT run on a normal 'push' or 'pull_request'.
  workflow_dispatch:

jobs:
  run-full-training:
    name: Execute Full MLOps Pipeline
    runs-on: ubuntu-latest

    steps:
      - name: 1. Check out code from repository
        uses: actions/checkout@v4

      - name: 2. Set up Python environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 3. Install all project dependencies
        run: |
          pip install -r requirements.txt
          pip install qiskit-optimization

      - name: 4. Run the end-to-end MLOps training pipeline
        run: |
          # This command runs the exact same training process as the main pipeline,
          # creating a new, retrained model and logging it to a new MLflow run.
          python run_pipeline.py

      - name: 5. Archive results from the retraining run
        # This saves all the new models and plots from the successful retraining.
        uses: actions/upload-artifact@v4
        with:
          name: retrained-pipeline-results
          path: |
            saved_models/
            mlruns/
            visualization*.png